# Generated by Django 5.2.7 on 2026-09-12 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('equipment', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file', models.FileField(upload_to='journal_exports/%Y/%m/', verbose_name='Файл')),
                ('entries_count', models.PositiveIntegerField(default=0, verbose_name='Количество записей')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_exports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='shifts.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Выгрузка журнала',
                'verbose_name_plural': 'Выгрузки журнала',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обращения')),
                ('source_location', models.CharField(max_length=250, verbose_name='Место поступления заявки')),
                ('reported_by', models.CharField(blank=True, max_length=200, verbose_name='Кто обратился')),
                ('problem', models.TextField(verbose_name='Описание проблемы')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Решено'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entries', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='equipment.equipment', verbose_name='Оборудование')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='shifts.shift', verbose_name='Смена')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Сменный журнал',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['status', 'priority'], name='journal_jou_status_aaef2e_idx'), models.Index(fields=['received_at'], name='journal_jou_receive_2c3ac8_idx')],
            },
        ),
    ]
