# Generated by Django 5.2.7 on 2026-09-13 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ('occurred_at', 'id'), 'verbose_name': 'Запись журнала', 'verbose_name_plural': 'Сменный журнал'},
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journal_jou_status_aaef2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journal_jou_receive_2c3ac8_idx',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='workshop',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='action_task',
            field=models.TextField(default='', verbose_name='Действие / Задача'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='downtime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время простоя'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('shift_start', 'Смена принята'), ('shift_end', 'Смена сдана'), ('work', 'Работа')], default='work', max_length=20, verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='equipment_line',
            field=models.CharField(blank=True, max_length=200, verbose_name='Оборудование / Линия'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег (км)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='print_head',
            field=models.CharField(blank=True, max_length=100, verbose_name='Печ. головка'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_records', to=settings.AUTH_USER_MODEL, verbose_name='Дежурный специалист'),
        ),
        migrations.AddField(
            model_name='journalexport',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Единый архив'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Решение (комментарий)'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['occurred_at'], name='journal_jou_occurre_986644_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type'], name='journal_jou_entry_t_d2ef18_idx'),
        ),
    ]
