# Generated by Django 5.2.7 on 2026-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Внешний ID'),
        ),
    ]
