# Generated by Django 5.2.7 on 2026-09-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название линии')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Производственная линия',
                'verbose_name_plural': 'Производственные линии',
                'ordering': ('workshop__name', 'sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('workshop', 'name'), name='unique_line_in_workshop')],
            },
        ),
    ]
