# Generated by Django 5.2.7 on 2026-09-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productionline'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
