# Generated by Django 5.2.7 on 2026-09-12 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Категория оборудования')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('inventory_number', models.CharField(max_length=60, unique=True, verbose_name='Инвентарный номер')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Производитель')),
                ('model_name', models.CharField(blank=True, max_length=150, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=150, verbose_name='Серийный номер')),
                ('commissioned_at', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('status', models.CharField(choices=[('operational', 'В работе'), ('maintenance', 'Обслуживание'), ('repair', 'Ремонт'), ('decommissioned', 'Списано')], default='operational', max_length=20, verbose_name='Состояние')),
                ('criticality', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=20, verbose_name='Критичность')),
                ('last_maintenance_at', models.DateField(blank=True, null=True, verbose_name='Последнее ТО')),
                ('next_maintenance_at', models.DateField(blank=True, null=True, verbose_name='Следующее ТО')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Учтено')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.productionsite', verbose_name='Производственная площадка')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.workshop', verbose_name='Цех')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='equipment.equipmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ('site__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('operational', 'В работе'), ('maintenance', 'Обслуживание'), ('repair', 'Ремонт'), ('decommissioned', 'Списано')], max_length=20, verbose_name='Состояние')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Запись состояния оборудования',
                'verbose_name_plural': 'История состояний оборудования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('to', 'Техническое обслуживание'), ('repair', 'Ремонт'), ('inspection', 'Осмотр'), ('calibration', 'Поверка/калибровка'), ('other', 'Прочее')], max_length=20, verbose_name='Вид работ')),
                ('performed_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата работ')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('performer', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, руб.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Запись о работах',
                'verbose_name_plural': 'Работы по оборудованию',
                'ordering': ('-performed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
    ]
