# Generated by Django 5.2.7 on 2026-09-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='print_head',
            field=models.CharField(blank=True, max_length=50, verbose_name='Печатающая головка'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='slot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Значение (первый/второй)'),
        ),
    ]
