# Generated by Django 5.2.7 on 2026-09-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_ip_address_equipment_print_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='inventory_number',
        ),
    ]
