# Generated by Django 5.2.7 on 2026-09-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='camera_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID камеры (Camera Control)'),
        ),
    ]
