# Generated by Django 5.2.7 on 2026-09-17 08:27

from django.db import migrations, models


def mark_cameras(apps, schema_editor):
    Equipment = apps.get_model("equipment", "Equipment")
    Equipment.objects.filter(camera_id__isnull=False).update(is_camera=True)


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_camera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_camera',
            field=models.BooleanField(default=False, verbose_name='Камера'),
        ),
        migrations.RunPython(mark_cameras, migrations.RunPython.noop),
    ]
