# Generated by Django 5.2.7 on 2026-09-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_assign_without_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
    ]
