# Generated by Django 5.2.7 on 2026-09-12 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата смены')),
                ('kind', models.CharField(choices=[('day', 'Дневная'), ('night', 'Ночная')], default='day', max_length=10, verbose_name='Тип смены')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время приёма')),
                ('opening_notes', models.TextField(blank=True, verbose_name='Примечания при приёме')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время сдачи')),
                ('closing_notes', models.TextField(blank=True, verbose_name='Примечания при сдаче')),
                ('equipment_condition', models.TextField(blank=True, verbose_name='Состояние оборудования')),
                ('inventory_notes', models.TextField(blank=True, verbose_name='Состояние склада')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_closed', to=settings.AUTH_USER_MODEL, verbose_name='Сдал смену')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_received', to=settings.AUTH_USER_MODEL, verbose_name='Передал смену')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_opened', to=settings.AUTH_USER_MODEL, verbose_name='Принял смену')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date', '-opened_at'),
            },
        ),
        migrations.CreateModel(
            name='ShiftCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новое'), ('good', 'Хорошее'), ('worn', 'Изношенное'), ('needs_repair', 'Требует ремонта'), ('broken', 'Неисправно')], max_length=20, verbose_name='Состояние при проверке')),
                ('wear_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Износ, %')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_checks', to='inventory.inventoryitem', verbose_name='Позиция склада')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='shifts.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Проверка позиции',
                'verbose_name_plural': 'Проверки позиций',
                'ordering': ('-created_at',),
            },
        ),
    ]
