# Generated by Django 5.2.7 on 2026-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус'),
        ),
    ]
