# Generated by Django 5.2.7 on 2026-09-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Смена принята'),
        ),
    ]
