# Generated by Django 5.2.7 on 2026-09-23 18:35

from django.db import migrations, models


def map_conditions(apps, schema_editor):
    """Старые состояния -> «Б/у» (пустые оставляем пустыми)."""
    ShiftCheck = apps.get_model("shifts", "ShiftCheck")
    ShiftCheck.objects.exclude(condition__in=["new", ""]).update(condition="used")


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shift_accepted'),
    ]

    operations = [
        migrations.RunPython(map_conditions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='shiftcheck',
            name='wear_percent',
        ),
        migrations.AlterField(
            model_name='shiftcheck',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('used', 'Б/у')], max_length=20, verbose_name='Состояние при проверке'),
        ),
    ]
