# Generated by Django 5.2.7 on 2026-09-12 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('inventory_number', models.CharField(blank=True, max_length=60, verbose_name='Инвентарный номер')),
                ('kind', models.CharField(choices=[('tool', 'Инструмент'), ('spare', 'Запасная часть'), ('consumable', 'Расходный материал'), ('device', 'Прибор/средство')], default='tool', max_length=20, verbose_name='Тип')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='Минимальный остаток')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('good', 'Хорошее'), ('worn', 'Изношенное'), ('needs_repair', 'Требует ремонта'), ('broken', 'Неисправно')], default='good', max_length=20, verbose_name='Состояние')),
                ('wear_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Износ, %')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('manufactured_at', models.DateField(blank=True, null=True, verbose_name='Дата производства')),
                ('last_verified_at', models.DateField(blank=True, null=True, verbose_name='Дата поверки/проверки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Позиция склада',
                'verbose_name_plural': 'Склад инструментов и запчастей',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('kind', models.CharField(choices=[('tool', 'Инструмент'), ('spare', 'Запасная часть'), ('consumable', 'Расходный материал'), ('device', 'Прибор/средство')], default='tool', max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Название места')),
                ('shelf_code', models.CharField(blank=True, max_length=50, verbose_name='Код полки/ячейки')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'ordering': ('workshop__name', 'shelf_code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('write_off', 'Списание'), ('correction', 'Инвентаризация')], max_length=20, verbose_name='Операция')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ('-created_at',),
            },
        ),
    ]
