# Generated by Django 5.2.7 on 2026-09-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='shifts.shift', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations', to='core.workshop', verbose_name='Цех'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.storagelocation', verbose_name='Место хранения'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['kind', 'condition'], name='inventory_i_kind_6fb0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location'], name='inventory_i_locatio_b552da_idx'),
        ),
    ]
