# Generated by Django 5.2.7 on 2026-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemtype_kind_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_types/', verbose_name='Иконка'),
        ),
    ]
