# Generated by Django 5.2.7 on 2026-09-22 11:55

import sys

import django.db.models.deletion
from django.db import migrations, models


def seed_storages(apps, schema_editor):
    if "test" in sys.argv:
        return
    Storage = apps.get_model("inventory", "Storage")
    InventoryItem = apps.get_model("inventory", "InventoryItem")

    default_storage, _ = Storage.objects.get_or_create(
        name="Новый склад", defaults={"sort_order": 0}
    )
    Storage.objects.get_or_create(name="Кабинет ЧЗ", defaults={"sort_order": 1})
    InventoryItem.objects.filter(storage__isnull=True).update(storage=default_storage)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_seed_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Склад')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ImageField(blank=True, upload_to='storages/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.storage', verbose_name='Склад'),
        ),
        migrations.RunPython(seed_storages, migrations.RunPython.noop),
    ]
