# Generated by Django 5.2.7 on 2026-09-23 18:35

from django.db import migrations, models


def map_conditions(apps, schema_editor):
    """Старые состояния (good/worn/needs_repair/broken) -> «Б/у»."""
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    InventoryItem.objects.exclude(condition="new").update(condition="used")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_assign_item_types'),
    ]

    operations = [
        migrations.RunPython(map_conditions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='wear_percent',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у')], default='new', max_length=20, verbose_name='Состояние'),
        ),
    ]
