# Generated by Django 5.2.7 on 2026-09-12 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название шаблона')),
                ('doc_type', models.CharField(choices=[('technical_report', 'Техническое заключение'), ('service_note', 'Служебная записка'), ('explanation', 'Объяснительная записка'), ('act', 'Акт'), ('other', 'Прочее')], default='technical_report', max_length=30, verbose_name='Тип документа')),
                ('title_template', models.CharField(max_length=300, verbose_name='Заголовок (шаблон)')),
                ('body', models.TextField(verbose_name='Тело документа (шаблон)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('workshops', models.ManyToManyField(blank=True, help_text='Если не выбрано ни одного цеха — шаблон доступен для всех.', related_name='document_templates', to='core.workshop', verbose_name='Доступен для цехов')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ('doc_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('number', models.CharField(blank=True, max_length=60, verbose_name='Номер документа')),
                ('doc_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата документа')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Поля документа')),
                ('body', models.TextField(blank=True, verbose_name='Сформированный текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('saved', 'Сохранён'), ('archived', 'В архиве')], default='saved', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='Файл DOCX')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.workshop', verbose_name='Цех')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-doc_date', '-created_at'),
            },
        ),
    ]
