# Generated by Django 5.2.7 on 2026-09-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(blank=True, choices=[('tz', 'Техническое заключение'), ('sl', 'Служебная записка')], default='', max_length=2, verbose_name='Вид документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttemplate', verbose_name='Шаблон'),
        ),
    ]
