# Generated by Django 5.2.7 on 2026-09-13 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=300, verbose_name='Проверка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Проверка чеклиста',
                'verbose_name_plural': 'Проверки чеклиста',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название группы')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа чеклиста',
                'verbose_name_plural': 'Группы чеклиста',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Название оборудования')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='checklists.checklistgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Оборудование чеклиста',
                'verbose_name_plural': 'Оборудование чеклиста',
                'ordering': ('group__sort_order', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('final', 'Сформирован')], default='draft', max_length=10, verbose_name='Статус')),
                ('file', models.FileField(blank=True, upload_to='checklists/%Y/%m/', verbose_name='Файл XLSX')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_performed', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='shifts.shift', verbose_name='Смена')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='core.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Чеклист оборудования',
                'verbose_name_plural': 'Чеклисты оборудования',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1 — Неудовлетворительно'), (2, '2 — Удовлетворительно'), (3, '3 — Готово к работе')], verbose_name='Оценка')),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklistcheck', verbose_name='Проверка')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklistmachine', verbose_name='Оборудование')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.equipmentchecklist', verbose_name='Чеклист')),
            ],
            options={
                'verbose_name': 'Результат проверки',
                'verbose_name_plural': 'Результаты проверок',
            },
        ),
        migrations.CreateModel(
            name='ChecklistMileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Пробег (км)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileages', to='checklists.checklistmachine', verbose_name='Оборудование')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileages', to='checklists.equipmentchecklist', verbose_name='Чеклист')),
            ],
            options={
                'verbose_name': 'Пробег головки',
                'verbose_name_plural': 'Пробеги головок',
            },
        ),
        migrations.AddConstraint(
            model_name='checklistmachine',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_machine_in_group'),
        ),
        migrations.AddConstraint(
            model_name='checklistresult',
            constraint=models.UniqueConstraint(fields=('checklist', 'machine', 'check_item'), name='unique_result_cell'),
        ),
        migrations.AddConstraint(
            model_name='checklistmileage',
            constraint=models.UniqueConstraint(fields=('checklist', 'machine'), name='unique_mileage_per_machine'),
        ),
    ]
