# Generated by Django 5.2.7 on 2026-09-15 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_equipmentchecklist_status'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Параметр')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Параметр чеклиста Markem',
                'verbose_name_plural': 'Параметры чеклиста Markem',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MarkemPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Принтер Markem',
                'verbose_name_plural': 'Принтеры Markem',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MarkemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('draft', 'В работе'), ('final', 'Сформирован')], default='draft', max_length=10, verbose_name='Статус')),
                ('file', models.FileField(blank=True, upload_to='markem/%Y/%m/', verbose_name='Файл XLSX')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markem_checked', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markem_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markem_performed', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markem_checklists', to='shifts.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Чеклист Markem Image 9450',
                'verbose_name_plural': 'Чеклисты Markem Image 9450',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MarkemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('value', models.CharField(blank=True, max_length=300, verbose_name='Значение')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='checklists.markemchecklist', verbose_name='Чеклист')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='checklists.markemparameter', verbose_name='Параметр')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='checklists.markemprinter', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Значение параметра Markem',
                'verbose_name_plural': 'Значения параметров Markem',
                'constraints': [models.UniqueConstraint(fields=('checklist', 'printer', 'parameter'), name='unique_markem_cell')],
            },
        ),
    ]
